name: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - master
    paths:
      - "front-web/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: git remote add dspesquisa https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push dspesquisa `git subtree split --prefix frontend master`:refs/heads/master --force
